# Generated by Django 6.0.3 on 2026-05-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0002_expenses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenses",
            name="expense",
            field=models.FloatField(),
        ),
    ]
